const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const PORT=process.env.PORT||8789;
const PUB=path.join(__dirname,'public');
const TZ='America/Chicago';
const USAGE_START_Y=2026,USAGE_START_M=8,USAGE_START_D=1;
const CALENDARS=[{name:'SMGSL League',url:'https://calendar.bluesombrero.com/api/v1/Calendar?instancekey=clubs&portalId=3766&id=47104525&key=YSGZTJHS'},{name:'SMGSL/SI Field Calendar',url:'https://calendar.bluesombrero.com/api/v1/Calendar?instancekey=clubs&portalId=3766&id=47104846&key=YDO7E8SV'}];
const TEAM_RE=/\b(longhorns?|aggies?|bruins?|gators?|sooners?|jayhawks?|lady\s+vols?|ducks?|bearcats?|tigers?|red\s+raiders?|cougars?|cowgirls?|nittany\s+lions?)\b/i;
const PUBLIC_MODE=String(process.env.PUBLIC_MODE||'false').toLowerCase()==='true';
const BOARD_PASSWORD=process.env.BOARD_PASSWORD||'';
const SECRET=process.env.SESSION_SECRET||crypto.createHash('sha256').update(BOARD_PASSWORD||'smgsl-dev').digest('hex');
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json; charset=utf-8','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.pdf':'application/pdf','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.png':'image/png'};
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim().split('=')).filter(x=>x.length===2));}
function token(){const exp=Date.now()+1000*60*60*24*14,raw=String(exp);return raw+'.'+crypto.createHmac('sha256',SECRET).update(raw).digest('hex');}
function authed(req){if(PUBLIC_MODE)return true;const t=cookies(req).smgsl_session;if(!t)return false;const [raw,sig]=t.split('.');if(!raw||!sig||Number(raw)<Date.now())return false;const want=crypto.createHmac('sha256',SECRET).update(raw).digest('hex');try{return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(want));}catch{return false;}}
function send(res,status,body,type='text/plain; charset=utf-8',headers={}){res.writeHead(status,{'Content-Type':type,...headers});res.end(body);}
function loginPage(msg=''){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>SMGSL Board Login</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#071526;color:#fff;margin:0;display:grid;min-height:100vh;place-items:center}.box{width:min(90vw,420px);background:#10243c;padding:28px;border-radius:18px;border:1px solid #29496c}h1{margin:0 0 8px}p{color:#b6c8dc}input,button{width:100%;font-size:17px;padding:14px;border-radius:12px;box-sizing:border-box}input{background:#091a2d;color:#fff;border:1px solid #37597d;margin:12px 0}button{background:#fff;color:#071526;border:0;font-weight:800}.err{color:#ffb4a9}</style></head><body><form class="box" method="POST" action="/login"><h1>SMGSL Board Hub</h1><p>Board-member access only.</p>${msg?`<p class="err">${msg}</p>`:''}<input name="password" type="password" placeholder="Board password" autofocus required><button>Sign in</button></form></body></html>`}
function parseForm(body){return Object.fromEntries(body.split('&').map(p=>p.split('=').map(v=>decodeURIComponent((v||'').replace(/\+/g,' ')))));}
function parts(date){const o=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {y:+o.year,m:+o.month,d:+o.day,h:+o.hour,min:+o.minute,s:+o.second};}
function offsetMs(date){const p=parts(date);return Date.UTC(p.y,p.m-1,p.d,p.h,p.min,p.s)-date.getTime();}
function centralDate(y,m,d,h=0,min=0){const wall=Date.UTC(y,m-1,d,h,min);let g=new Date(wall),o=offsetMs(g),out=new Date(wall-o),o2=offsetMs(out);if(o2!==o)out=new Date(wall-o2);return out;}
function ymd(date){const p=parts(date);return `${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`;}
function addMinutes(d,m){return new Date(d.getTime()+m*60000);}
function addDays(d,n){const p=parts(d),noon=centralDate(p.y,p.m,p.d,12),tmp=new Date(noon.getTime()+n*86400000),q=parts(tmp);return centralDate(q.y,q.m,q.d,12);}
function parseCalDate(s){if(!s)return null;const m=s.match(/(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?/);if(!m)return null;const y=+m[1],mo=+m[2],d=+m[3],h=+(m[4]||0),mi=+(m[5]||0);return /Z$/.test(s)?new Date(Date.UTC(y,mo-1,d,h,mi)):centralDate(y,mo,d,h,mi);}
function unescapeICS(s=''){return s.replace(/\\n/gi,' ').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\').trim();}
function parseICS(text,source){const unfolded=text.replace(/\r?\n[ \t]/g,''),blocks=unfolded.split('BEGIN:VEVENT').slice(1).map(x=>x.split('END:VEVENT')[0]),out=[];for(const b of blocks){const get=k=>{const m=b.match(new RegExp('(?:^|\\n)'+k+'(?:;[^:]*)?:([^\\n\\r]+)','i'));return m?m[1].trim():''};const start=parseCalDate(get('DTSTART')),end=parseCalDate(get('DTEND'));if(!start||!end)continue;out.push({source,uid:get('UID'),start,end,summary:unescapeICS(get('SUMMARY')),location:unescapeICS(get('LOCATION')),description:unescapeICS(get('DESCRIPTION')),categories:unescapeICS(get('CATEGORIES')),rrule:get('RRULE')});}return out;}
function text(e){return `${e.summary||''} ${e.location||''} ${e.description||''} ${e.categories||''}`;}
function fieldNumbers(e){const t=text(e),nums=[];for(const re of [/(?:field|fld)\s*(?:#|no\.?|number)?\s*[-:]?\s*([1-8])\b/ig,/\bSMGSL\s*[-–—:]?\s*(?:field\s*)?([1-8])\b/ig,/\b(?:F|Fld)\s*#?\s*([1-8])\b/ig]){let m;while((m=re.exec(t)))nums.push(+m[1]);}return [...new Set(nums)].sort((a,b)=>a-b);}
function isSI(e){return /(^|\W)SI(\W|$)|sports\s*inc|sudden\s*impact|schneider|oglesby|fontenot|joiner|ray\s+practice|williams\s+practice|forman\s+practice/i.test(text(e));}
function isSMGSL(e){const t=text(e);return !isSI(e)&&(TEAM_RE.test(t)||/\bSMGSL\b/i.test(t));}
function isPractice(e){return /practice/i.test(text(e))||isSI(e)||isSMGSL(e);}
function sameDay(a,b){return ymd(a)===ymd(b);}
function overlaps(a1,a2,b1,b2){return a1<b2&&a2>b1;}
function endTime(e){const min=isSI(e)?addMinutes(e.start,180):e.end;return e.end>min?e.end:min;}
function makeWeeklyTemplates(baseEvents,anchor){const cutoffPast=addDays(anchor,-10),cutoffFuture=addDays(anchor,10),map=new Map();for(const e of baseEvents){if(!isPractice(e)||!fieldNumbers(e).length||e.start<cutoffPast||e.start>cutoffFuture)continue;const p=parts(e.start),dow=new Date(Date.UTC(p.y,p.m-1,p.d)).getUTCDay(),dur=Math.max(30,(endTime(e)-e.start)/60000);for(const f of fieldNumbers(e)){const owner=isSI(e)?'SI':(isSMGSL(e)?'SMGSL':'OTHER');if(owner==='OTHER')continue;const key=[owner,dow,p.h,p.min,Math.round(dur),f,(e.summary||'').toLowerCase().replace(/\s+/g,' ').trim()].join('|');if(!map.has(key))map.set(key,{owner,dow,h:p.h,min:p.min,durationMinutes:dur,fieldNumber:f,summary:e.summary,location:e.location});}}return [...map.values()];}
function projectedFromTemplates(templates,from,to,smgslCutoff){const out=[];for(let day=new Date(from);day<to;day=addDays(day,1)){const p=parts(day),dow=new Date(Date.UTC(p.y,p.m-1,p.d)).getUTCDay();for(const t of templates){if(t.dow!==dow)continue;const start=centralDate(p.y,p.m,p.d,t.h,t.min);if(start<from||start>=to||(t.owner==='SMGSL'&&start>=smgslCutoff))continue;let end=addMinutes(start,t.durationMinutes);if(end>to)end=to;if(end>start)out.push({source:'weekly-template',start,end,summary:t.summary,location:t.location,fieldNumber:t.fieldNumber,owner:t.owner,projected:true});}}return out;}
function mergeUsageEvents(actual,projected){const seen=new Map();for(const e of [...projected,...actual]){const k=[e.fieldNumber,ymd(e.start),parts(e.start).h,parts(e.start).min,e.owner,(e.summary||'').toLowerCase().replace(/\s+/g,' ').trim()].join('|');if(!seen.has(k)||!e.projected)seen.set(k,e);}return [...seen.values()];}
function actualUsageEvents(baseEvents,from,to){const out=[];for(const e of baseEvents){const owner=isSI(e)?'SI':(isSMGSL(e)?'SMGSL':'OTHER');if(owner==='OTHER'||!isPractice(e))continue;const rawEnd=endTime(e);if(rawEnd<=from||e.start>=to)continue;const start=e.start<from?from:e.start,end=rawEnd>to?to:rawEnd;if(end<=start)continue;for(const f of fieldNumbers(e))out.push({source:e.source,start,end,summary:e.summary,location:e.location,fieldNumber:f,owner,projected:false});}return out;}
function usageEventsSince(baseEvents,from,to,anchor,smgslCutoff){return mergeUsageEvents(actualUsageEvents(baseEvents,from,to),projectedFromTemplates(makeWeeklyTemplates(baseEvents,anchor),from,to,smgslCutoff));}
function normalizedEvents(baseEvents,from,to,smgslCutoff){const projected=projectedFromTemplates(makeWeeklyTemplates(baseEvents,from),from,to,smgslCutoff),actual=[];for(const e of baseEvents){if(e.end<from||e.start>=to)continue;for(const f of fieldNumbers(e))actual.push({source:e.source,start:e.start,end:endTime(e),summary:e.summary,location:e.location,fieldNumber:f,owner:isSI(e)?'SI':(isSMGSL(e)?'SMGSL':'OTHER'),projected:false});}return mergeUsageEvents(actual,projected);}
function openWindow(day){const p=parts(day),dow=new Date(Date.UTC(p.y,p.m-1,p.d)).getUTCDay();if(dow>=2&&dow<=5)return [centralDate(p.y,p.m,p.d,18),centralDate(p.y,p.m,p.d,21)];if(dow===0)return [centralDate(p.y,p.m,p.d,9),centralDate(p.y,p.m,p.d,21)];return null;}
function candidateStarts(day){const win=openWindow(day);if(!win)return [];const out=[];for(let t=new Date(win[0]);addMinutes(t,90)<=win[1];t=addMinutes(t,30))out.push(new Date(t));return out;}
function unionBusyMinutes(events,start,end){const ints=events.map(e=>[e.start>start?e.start:start,e.end<end?e.end:end]).filter(x=>x[1]>x[0]).sort((a,b)=>a[0]-b[0]);if(!ints.length)return 0;let total=0,s=ints[0][0],e=ints[0][1];for(let i=1;i<ints.length;i++){if(ints[i][0]<=e){if(ints[i][1]>e)e=ints[i][1];}else{total+=(e-s)/60000;s=ints[i][0];e=ints[i][1];}}return total+(e-s)/60000;}
function summarizeUsage(events){let si=0,sm=0;for(const e of events){const m=Math.max(0,(e.end-e.start)/60000);if(e.owner==='SI')si+=m;else if(e.owner==='SMGSL')sm+=m;}return {siFieldHours:+(si/60).toFixed(1),smgslFieldHours:+(sm/60).toFixed(1)};}
function currentTotalFieldHours(events){let minutes=0;for(let f=1;f<=8;f++)minutes+=unionBusyMinutes(events.filter(e=>e.fieldNumber===f),new Date(0),new Date(8640000000000000));return +(minutes/60).toFixed(1);}
function capacitySummary(events,now,horizon){let total=0,busy=0;for(let day=new Date(now);day<horizon;day=addDays(day,1)){const win=openWindow(day);if(!win)continue;const mins=(win[1]-win[0])/60000;total+=mins*8;for(let f=1;f<=8;f++)busy+=unionBusyMinutes(events.filter(e=>e.fieldNumber===f&&sameDay(e.start,day)),win[0],win[1]);}return {totalFieldHours:+(total/60).toFixed(1),occupiedFieldHours:+(busy/60).toFixed(1),availableFieldHours:+((total-busy)/60).toFixed(1)};}
function availability(baseEvents,days=21,feedStats=[]){const instantNow=new Date(),np=parts(instantNow),today=centralDate(np.y,np.m,np.d),horizon=addDays(today,days),smgslCutoff=centralDate(np.y,11,2),usageStart=centralDate(USAGE_START_Y,USAGE_START_M,USAGE_START_D),availabilityEvents=normalizedEvents(baseEvents,today,horizon,smgslCutoff),currentUsageEvents=usageEventsSince(baseEvents,usageStart,instantNow,today,smgslCutoff),slots=[];for(let d=0;d<days;d++){const day=addDays(today,d);for(let f=1;f<=8;f++){const busy=availabilityEvents.filter(e=>e.fieldNumber===f&&sameDay(e.start,day));for(const start of candidateStarts(day)){const end=addMinutes(start,90);if(!busy.some(e=>overlaps(start,end,e.start,e.end)))slots.push({field:`Field ${f}`,fieldNumber:f,start,end,durationMinutes:90});}}}const si=currentUsageEvents.filter(e=>e.owner==='SI').map(e=>({field:`Field ${e.fieldNumber}`,fieldNumber:e.fieldNumber,start:e.start,end:e.end,summary:e.summary,location:e.location,durationMinutes:(e.end-e.start)/60000,projected:e.projected})),usage=summarizeUsage(currentUsageEvents);usage.currentTotalFieldHours=currentTotalFieldHours(currentUsageEvents);const capacity=capacitySummary(availabilityEvents,today,horizon);slots.sort((a,b)=>a.start-b.start||a.fieldNumber-b.fieldNumber);si.sort((a,b)=>a.start-b.start||a.fieldNumber-b.fieldNumber);return {fields:Array.from({length:8},(_,i)=>`Field ${i+1}`),slots,si,usage:{...usage,...capacity,windowDays:days,usageYear:np.y,usageStart:'2026-08-01',usageThrough:ymd(instantNow)},diagnostics:{feeds:feedStats,baseEventCount:baseEvents.length,templateCount:makeWeeklyTemplates(baseEvents,today).length,availabilityOccupancyEvents:availabilityEvents.length,currentUsageEvents:currentUsageEvents.length},rules:{timeZone:TZ,normalPracticeMinutes:90,siPracticeMinutes:180,tuesdayFridayOpen:'18:00',dailyClose:'21:00',sundayOpen:'09:00',mondayAvailable:false,saturdayAvailable:false,fieldCount:8}};}
async function loadCalendars(){const all=[],stats=[];for(const c of CALENDARS){try{const r=await fetch(c.url,{headers:{'User-Agent':'SMGSL-Board-Hub/1.0','Accept':'text/calendar,text/plain,*/*'}}),txt=await r.text();if(!r.ok||!/BEGIN:VCALENDAR/i.test(txt)){stats.push({name:c.name,ok:false,status:r.status});continue;}const ev=parseICS(txt,c.name);all.push(...ev);stats.push({name:c.name,ok:true,eventCount:ev.length});}catch(e){stats.push({name:c.name,ok:false,error:e.message});}}if(!all.length)throw new Error('No SMGSL calendar events could be loaded');return {all,stats};}
async function calendarData(){const {all,stats}=await loadCalendars();return availability(all,21,stats);}
async function fieldLookup(date,time,field){if(!/^\d{4}-\d{2}-\d{2}$/.test(date||'')||!/^\d{2}:\d{2}$/.test(time||'')||field<1||field>8)throw new Error('Valid date, time and field 1-8 are required');const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number),at=centralDate(y,m,d,h,min),dayStart=centralDate(y,m,d),dayEnd=addDays(dayStart,1),{all}=await loadCalendars();let events=normalizedEvents(all,dayStart,dayEnd,centralDate(y,11,2));let matches=events.filter(e=>e.fieldNumber===field&&e.start<=at&&e.end>at);matches.sort((a,b)=>Number(a.projected)-Number(b.projected)||a.start-b.start);return {date,time,displayTime:new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit'}).format(at),field,matches:matches.map(e=>({fieldNumber:e.fieldNumber,start:e.start,end:e.end,summary:e.summary,location:e.location,owner:e.owner,source:e.source,projected:!!e.projected}))};}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/login')return send(res,200,loginPage(),'text/html; charset=utf-8');if(req.method==='POST'&&u.pathname==='/login'){let body='';req.on('data',c=>body+=c);return req.on('end',()=>{const p=parseForm(body).password||'';let ok=false;if(BOARD_PASSWORD&&p.length===BOARD_PASSWORD.length){try{ok=crypto.timingSafeEqual(Buffer.from(p),Buffer.from(BOARD_PASSWORD));}catch{}}if(ok)return send(res,302,'','text/plain',{'Set-Cookie':`smgsl_session=${token()}; HttpOnly; SameSite=Lax; Max-Age=1209600; Path=/`,'Location':'/'});return send(res,401,loginPage('Incorrect password.'),'text/html; charset=utf-8');});}if(req.method==='GET'&&u.pathname==='/logout')return send(res,302,'','text/plain',{'Set-Cookie':'smgsl_session=; Max-Age=0; Path=/','Location':'/login'});if(!authed(req))return send(res,302,'','text/plain',{'Location':'/login'});if(u.pathname==='/api/fields'){try{return send(res,200,JSON.stringify(await calendarData()),'application/json; charset=utf-8')}catch(e){return send(res,502,JSON.stringify({error:e.message}),'application/json; charset=utf-8')}}if(u.pathname==='/api/field-lookup'){try{return send(res,200,JSON.stringify(await fieldLookup(u.searchParams.get('date'),u.searchParams.get('time'),Number(u.searchParams.get('field')))),'application/json; charset=utf-8')}catch(e){return send(res,400,JSON.stringify({error:e.message}),'application/json; charset=utf-8')}}let rel=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),fp=path.join(PUB,rel);if(!fp.startsWith(PUB))return send(res,403,'Forbidden');fs.readFile(fp,(err,data)=>{if(err)return send(res,404,'Not Found');send(res,200,data,mime[path.extname(fp)]||'application/octet-stream')});});
server.listen(PORT,'0.0.0.0',()=>console.log('SMGSL Board Hub on '+PORT));